repositoryName: base-repository
repositoryOwner: athaydaooo
imageTag: 0247ace72653c00a212b81090746d8aaf1b5dacf
replicaCount: 2
service:
  type: ClusterIP
  internalPort: 3000
  externalPort: 443
ingress:
  enabled: true
  className: "nginx"
  annotations: {nginx.ingress.kubernetes.io/ssl-redirect: "true", nginx.ingress.kubernetes.io/force-ssl-redirect: "true", nginx.ingress.kubernetes.io/rewrite-target: /}
  hosts:
    - host: teste.guaruja.sp.gov.br
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - teste.guaruja.sp.gov.br
      secretName: guarujaspgovbr-tls
