repositoryName: base-repository
repositoryOwner: athaydaooo
imageTag: 1249be65051012dac5e6b86b36e8af4fd8fe62e5
replicaCount: 2
service:
  type: ClusterIP
  internalPort: 3000
  externalPort: 443
ingress:
  enabled: true
  className: "nginx"
  annotations:
    {
      nginx.ingress.kubernetes.io/ssl-redirect: "true",
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true",
      nginx.ingress.kubernetes.io/rewrite-target: /,
    }
  hosts:
    - host: teste.guaruja.sp.gov.br
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - teste.guaruja.sp.gov.br
      secretName: guarujaspgovbr-tls
