name: CD - Deploy com ArgoCD

on:
  push:
    branches: [main]

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment variables from vars.yaml
        id: set-env-vars
        run: |
          export REPOSITORY_NAME=$(yq eval '.repositoryName' ../../devops/vars.yaml)
          export REPOSITORY_OWNER=$(yq eval '.repositoryOwner' ../../devops/vars.yaml)

          echo "REPOSITORY_NAME=${REPOSITORY_NAME}"
          echo "REPOSITORY_OWNER=${REPOSITORY_OWNER}"

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ env.REPOSITORY_OWNER }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.REPOSITORY_OWNER }}/${{ env.REPOSITORY_NAME }}
          tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy with ArgoCD
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment variables from vars.yaml
        id: set-env-vars
        run: |
          export REPOSITORY_NAME=$(yq eval '.repositoryName' ../../devops/vars.yaml)
          export REPOSITORY_OWNER=$(yq eval '.repositoryOwner' ../../devops/vars.yaml)

          echo "REPOSITORY_NAME=${REPOSITORY_NAME}"
          echo "REPOSITORY_OWNER=${REPOSITORY_OWNER}"

      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: Update Kubernetes manifests
        run: |
          cd devops
          kustomize edit set image app=${{ env.REPOSITORY_OWNER }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }}
          cat kustomization.yaml

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git diff --exit-code || (git commit -am "create image to version ${{ github.sha }}")
          git push
