name: CD - Deploy com ArgoCD

on:
  push:
    branches: [main]

env:
  DOCKER_USERNAME: athaydaooo
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: base-repository
  REPOSITORY_NAME: base-repository
  REPOSITORY_OWNER: athaydaooo

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          context: .
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}
          tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy with ArgoCD
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: Update Kubernetes manifests
        run: |
          cd devops
          kustomize edit set image app=${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ github.sha }}
          cat kustomization.yaml

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git diff --exit-code || (git commit -am "create image to version ${{ github.sha }}")

      - name: Push to GitHub
        uses: ad-m/github-push-action@master
