name: CD - Deploy com ArgoCD

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - "devops/**"
      - ".github/**"
      - ".husky/**"

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
  REPOSITORY_NAME: ${{ github.repository }}
  REPOSITORY_OWNER: ${{ github.repository_owner }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}
          tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy with ArgoCD
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Change `imageTag` on values.yaml
        run: |
          yq e -i '.imageTag = "${{ github.sha }}"' devops/values.yaml

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git diff --exit-code || (git commit -am "create image to version ${{ github.sha }}")
          git push
