name: CD - Deploy com ArgoCD

on:
  push:
    branches: [main]

env:
  DOCKER_USERNAME: athaydaooo
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: base-repository
  REPOSITORY_NAME: base-repository
  REPOSITORY_OWNER: athaydaooo

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Docker repo if needed
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -u "$DOCKER_USERNAME:$DOCKER_PASSWORD" "https://hub.docker.com/v2/repositories/$DOCKER_USERNAME/$DOCKER_REPO/")
          if [ "$RESPONSE" -eq 404 ]; then
            echo "Repositório não encontrado. Criando..."
            curl -s -X POST "https://hub.docker.com/v2/repositories/$DOCKER_USERNAME/$DOCKER_REPO/" \
              -H "Content-Type: application/json" \
              -u "$DOCKER_USERNAME:$DOCKER_PASSWORD" \
              -d '{"namespace": "'$DOCKER_USERNAME'", "name": "'$DOCKER_REPO'", "is_private": false}'
          else
            echo "Repositório já existe."
          fi

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}
          tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy with ArgoCD
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: Update Kubernetes manifests
        run: |
          cd devops
          kustomize edit set image app=${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ github.sha }}
          cat kustomization.yaml

      - name: Commit changes
        run: |
          git diff --exit-code || (git commit -am "create image to version ${{ github.sha }}")

      - name: Push to GitHub
        uses: ad-m/github-push-action@master
